version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=ProductDb;User=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    ports:
      - "5001:8080"  
    command: >
      sh -c "dotnet ef database update && dotnet LemonadeStandApi.dll"

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app  
      - /app/node_modules  
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  sqlserverdata:


# version: '3.8'
#
# services:
#   db:
#     image: mcr.microsoft.com/mssql/server:2019-latest
#     container_name: sql_server
#     environment:
#       SA_PASSWORD: "YourStrong!Passw0rd"
#       ACCEPT_EULA: "Y"
#     ports:
#       - "1433:1433"
#     volumes:
#       - sqlserverdata:/var/opt/mssql
#
# volumes:
#   sqlserverdata:
